apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app1-deployment
  namespace: dev
spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: app1
  template:
    metadata: 
      labels: 
        app1: app1
    spec: 
      containers: 
        - name: app1-container
          image: nginx:latest
          ports: 
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: app1-service
  namespace: dev
spec: 
  type: ClusterIP
  selector:
    app: app1
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80
